name = "alg_ch0"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["AlgCh0"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "AlgCh0"
